### ISSUE TITLE
指定hosts时报错

### ISSUE THREAD

**Issue by puteulanus** [GameXG/TcpRoute2#44]
本地有简单的HTTP服务， http://127.0.0.1/file/hosts.txt 的内容为一行 127.0.0.1 localhost 。
在配置中指定本地hosts报错，删除后错误消失。
格式完全相同的 pgl.yoyo.org 的hosts不会引发问题。

顺便，指定与配置文件同目录的 whitelist.txt （Path="whitelist.txt"）之后似乎并没有加载白名单，在加入 google.com 之后依然可以正常访问。尝试过重启软件，依旧如此。

新加的几个功能的配置建议做一下判断，当缺少子项或者某选项不存在时，使用默认值启动，或者输出特定的错误信息后退出。比如[[Hosts]]不存在时启动过程中会直接崩溃掉，必需在同目录新建一个hosts指定才可以顺利运行，但实际上hosts应该不属于必选配置。

配置文件为：
```
[[Hosts]]
Path="http://127.0.0.1/file/hosts.txt"
Type="base"
UpdateInterval="24h"

[[Hosts]]
Path="http://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&showintro=0&mimetype=plaintext"
Type="base"
UpdateInterval="24h"
```
报错信息：
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x50a4fa]

goroutine 26 [running]:
github.com/gamexg/TcpRoute2/ufile.(*UFile).loop_watcher(0x110d4600)
        /home/travis/gopath/src/github.com/gamexg/TcpRoute2/ufile/ufile.go:283 +
0x6a
github.com/gamexg/TcpRoute2/ufile.(*UFile).loop.func2(0x110d4600, 0x11150c20)
        /home/travis/gopath/src/github.com/gamexg/TcpRoute2/ufile/ufile.go:270 +
0x21
created by github.com/gamexg/TcpRoute2/ufile.(*UFile).loop
        /home/travis/gopath/src/github.com/gamexg/TcpRoute2/ufile/ufile.go:272 +
0x90

goroutine 1 [runnable, locked to thread]:
syscall.Syscall(0x71a28cd3, 0x2, 0x734, 0x7fffffff, 0x0, 0x92d48, 0x0, 0x1b9e)
        /home/travis/.gimme/versions/go1.5.linux.amd64/src/runtime/syscall_windo
ws.go:128 +0x4a
syscall.listen(0x734, 0x7fffffff, 0x0, 0x0)
        /home/travis/.gimme/versions/go1.5.linux.amd64/src/syscall/zsyscall_wind
ows.go:1464 +0x5f
syscall.Listen(0x734, 0x7fffffff, 0x0, 0x0)
        /home/travis/.gimme/versions/go1.5.linux.amd64/src/syscall/syscall_windo
ws.go:745 +0x35
net.(*netFD).listenStream(0x110e1ce0, 0x311f4850, 0x1115a8a0, 0x7fffffff, 0x0, 0
x0)
        /home/travis/.gimme/versions/go1.5.linux.amd64/src/net/sock_posix.go:166
 +0x205
net.socket(0x73362c, 0x3, 0x2, 0x1, 0x0, 0x0, 0x311f4850, 0x1115a8a0, 0x0, 0x0,
...)
        /home/travis/.gimme/versions/go1.5.linux.amd64/src/net/sock_posix.go:76
+0x184
net.internetSocket(0x73362c, 0x3, 0x311f4850, 0x1115a8a0, 0x0, 0x0, 0x0, 0x0, 0x
0, 0x0, ...)
        /home/travis/.gimme/versions/go1.5.linux.amd64/src/net/ipsock_posix.go:1
60 +0xe6
net.ListenTCP(0x73362c, 0x3, 0x1115a8a0, 0x311f4830, 0x0, 0x0)
        /home/travis/.gimme/versions/go1.5.linux.amd64/src/net/tcpsock_posix.go:
329 +0x15b
net.Listen(0x73362c, 0x3, 0x110dadb0, 0xc, 0x0, 0x0, 0x0, 0x0)
        /home/travis/.gimme/versions/go1.5.linux.amd64/src/net/dial.go:395 +0x38
0
main.(*Server).ListAndServe(0x110d3050, 0x0, 0x0)
        /home/travis/gopath/src/github.com/GameXG/TcpRoute2/server.go:65 +0x63
main.main()
        /home/travis/gopath/src/github.com/GameXG/TcpRoute2/main.go:84 +0x8e3

goroutine 5 [chan receive]:
github.com/golang/glog.(*loggingT).flushDaemon(0x8da1e0)
        /home/travis/gopath/src/github.com/golang/glog/glog.go:882 +0x61
created by github.com/golang/glog.init.1
        /home/travis/gopath/src/github.com/golang/glog/glog.go:410 +0x21d

goroutine 17 [runnable]:
github.com/gamexg/TcpRoute2/netchan.(*hostsDns).loop(0x1113c340, 0x110d4f00, 0x1
10d2db0)
        /home/travis/gopath/src/github.com/gamexg/TcpRoute2/netchan/dnschan_host
s.go:169
created by github.com/gamexg/TcpRoute2/netchan.(*hostsDns).Config
        /home/travis/gopath/src/github.com/gamexg/TcpRoute2/netchan/dnschan_host
s.go:163 +0xcce

goroutine 7 [semacquire]:
sync.runtime_Semacquire(0x11150c2c)
        /home/travis/.gimme/versions/go1.5.linux.amd64/src/runtime/sema.go:43 +0
x26
sync.(*WaitGroup).Wait(0x11150c20)
        /home/travis/.gimme/versions/go1.5.linux.amd64/src/sync/waitgroup.go:126
 +0xa4
github.com/gamexg/TcpRoute2/ufile.(*UFile).loop(0x110d4600)
        /home/travis/gopath/src/github.com/gamexg/TcpRoute2/ufile/ufile.go:274 +
0x9c
created by github.com/gamexg/TcpRoute2/ufile.NewUFile
        /home/travis/gopath/src/github.com/gamexg/TcpRoute2/ufile/ufile.go:81 +0
x209

goroutine 8 [runnable]:
github.com/gamexg/TcpRoute2/netchan.(*hostsDns).loop(0x1113c340, 0x110d4600, 0x1
10d24e0)
        /home/travis/gopath/src/github.com/gamexg/TcpRoute2/netchan/dnschan_host
s.go:169
created by github.com/gamexg/TcpRoute2/netchan.(*hostsDns).Config
        /home/travis/gopath/src/github.com/gamexg/TcpRoute2/netchan/dnschan_host
s.go:163 +0xcce

goroutine 9 [runnable]:
github.com/gamexg/TcpRoute2/netchan.searchBlackIP()
        /home/travis/gopath/src/github.com/gamexg/TcpRoute2/netchan/dnschan.go:7
0
created by github.com/gamexg/TcpRoute2/netchan.init.1
        /home/travis/gopath/src/github.com/gamexg/TcpRoute2/netchan/dnschan.go:6
7 +0x24a

goroutine 10 [runnable]:
github.com/go-fsnotify/fsnotify.(*Watcher).readEvents(0x110d2b70)
        /home/travis/gopath/src/github.com/go-fsnotify/fsnotify/windows.go:373
created by github.com/go-fsnotify/fsnotify.NewWatcher
        /home/travis/gopath/src/github.com/go-fsnotify/fsnotify/windows.go:46 +0
x2d5

goroutine 11 [runnable]:
github.com/gamexg/TcpRoute2/ufile.(*UFile).loop(0x110d4f00)
        /home/travis/gopath/src/github.com/gamexg/TcpRoute2/ufile/ufile.go:261
created by github.com/gamexg/TcpRoute2/ufile.NewUFile
        /home/travis/gopath/src/github.com/gamexg/TcpRoute2/ufile/ufile.go:81 +0
x209

goroutine 12 [runnable]:
github.com/gamexg/TcpRoute2/ufile.(*UFile).down(0x110d4f00, 0x110d4fc0, 0x0, 0x1
0)
        /home/travis/gopath/src/github.com/gamexg/TcpRoute2/ufile/ufile.go:116
created by github.com/gamexg/TcpRoute2/ufile.(*UFile).Add
        /home/travis/gopath/src/github.com/gamexg/TcpRoute2/ufile/ufile.go:211 +
0x57d

goroutine 13 [select]:
net/http.(*Transport).getConn(0x11110a80, 0x11110ee0, 0x0, 0x11124300, 0x4, 0x11
150950, 0xf, 0x0, 0x0, 0x0)
        /home/travis/.gimme/versions/go1.5.linux.amd64/src/net/http/transport.go
:554 +0x533
net/http.(*Transport).RoundTrip(0x11110a80, 0x11110ee0, 0xaf, 0x0, 0x0)
        /home/travis/.gimme/versions/go1.5.linux.amd64/src/net/http/transport.go
:228 +0x3b9
net/http.send(0x11110ee0, 0x311f4288, 0x11110a80, 0x111245a0, 0x0, 0x0)
        /home/travis/.gimme/versions/go1.5.linux.amd64/src/net/http/client.go:22
0 +0x40a
net/http.(*Client).send(0x8d9fe0, 0x11110ee0, 0x5c, 0x0, 0x0)
        /home/travis/.gimme/versions/go1.5.linux.amd64/src/net/http/client.go:14
3 +0xf5
net/http.(*Client).doFollowingRedirects(0x8d9fe0, 0x11110ee0, 0x7ccc90, 0x0, 0x0
, 0x0)
        /home/travis/.gimme/versions/go1.5.linux.amd64/src/net/http/client.go:38
0 +0x9bd
net/http.(*Client).Get(0x8d9fe0, 0x11124300, 0x5c, 0x110d2bd0, 0x0, 0x0)
        /home/travis/.gimme/versions/go1.5.linux.amd64/src/net/http/client.go:30
6 +0x92
net/http.Get(0x11124300, 0x5c, 0x11159f9c, 0x0, 0x0)
        /home/travis/.gimme/versions/go1.5.linux.amd64/src/net/http/client.go:28
1 +0x3f
github.com/gamexg/TcpRoute2/ufile.(*UFile).down(0x110d4f00, 0x110d5040, 0x0, 0x0
)
        /home/travis/gopath/src/github.com/gamexg/TcpRoute2/ufile/ufile.go:133 +
0x241
created by github.com/gamexg/TcpRoute2/ufile.(*UFile).Add
        /home/travis/gopath/src/github.com/gamexg/TcpRoute2/ufile/ufile.go:211 +
0x57d

goroutine 14 [select]:
net.lookupIPDeadline(0x11150950, 0xc, 0xce2ad31a, 0xe, 0x7a56c0, 0x8da060, 0x0,
0x0, 0x0, 0x0, ...)
        /home/travis/.gimme/versions/go1.5.linux.amd64/src/net/lookup.go:109 +0x
5d3
net.internetAddrList(0x73362c, 0x3, 0x11150950, 0xf, 0xce2ad31a, 0xe, 0x7a56c0,
0x8da060, 0x0, 0x0, ...)
        /home/travis/.gimme/versions/go1.5.linux.amd64/src/net/ipsock.go:252 +0x
584
net.resolveAddrList(0x735550, 0x4, 0x73362c, 0x3, 0x11150950, 0xf, 0xce2ad31a, 0
xe, 0x7a56c0, 0x8da060, ...)
        /home/travis/.gimme/versions/go1.5.linux.amd64/src/net/dial.go:153 +0x36
4
net.(*Dialer).Dial(0x110d4380, 0x73362c, 0x3, 0x11150950, 0xf, 0x0, 0x0, 0x0, 0x
0)
        /home/travis/.gimme/versions/go1.5.linux.amd64/src/net/dial.go:209 +0x15
0
net.(*Dialer).Dial-fm(0x73362c, 0x3, 0x11150950, 0xf, 0x0, 0x0, 0x0, 0x0)
        /home/travis/.gimme/versions/go1.5.linux.amd64/src/net/http/transport.go
:38 +0x58
net/http.(*Transport).dial(0x11110a80, 0x73362c, 0x3, 0x11150950, 0xf, 0x0, 0x0,
 0x0, 0x0)
        /home/travis/.gimme/versions/go1.5.linux.amd64/src/net/http/transport.go
:499 +0x68
net/http.(*Transport).dialConn(0x11110a80, 0x0, 0x11124300, 0x4, 0x11150950, 0xf
, 0x0, 0x0, 0x0)
        /home/travis/.gimme/versions/go1.5.linux.amd64/src/net/http/transport.go
:596 +0x1619
net/http.(*Transport).getConn.func4(0x11110a80, 0x0, 0x11124300, 0x4, 0x11150950
, 0xf, 0x110d5100)
        /home/travis/.gimme/versions/go1.5.linux.amd64/src/net/http/transport.go
:549 +0x4d
created by net/http.(*Transport).getConn
        /home/travis/.gimme/versions/go1.5.linux.amd64/src/net/http/transport.go
:551 +0x20d

goroutine 16 [runnable, locked to thread]:
syscall.Syscall6(0x71a22899, 0x4, 0x1113de80, 0x0, 0x11152ee4, 0x11152e3c, 0x0,
0x0, 0xc, 0x1113de80, ...)
        /home/travis/.gimme/versions/go1.5.linux.amd64/src/runtime/syscall_windo
ws.go:139 +0x4a
syscall.GetAddrInfoW(0x1113de80, 0x0, 0x11152ee4, 0x11152e3c, 0x0, 0x0)
        /home/travis/.gimme/versions/go1.5.linux.amd64/src/syscall/zsyscall_wind
ows.go:1670 +0x77
net.newLookupIP(0x11150950, 0xc, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/travis/.gimme/versions/go1.5.linux.amd64/src/net/lookup_windows.go
:118 +0x126
net.glob.func15(0x7ccc0c, 0x11150950, 0xc, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/travis/.gimme/versions/go1.5.linux.amd64/src/net/hook.go:10 +0x44
net.lookupIPDeadline.func1(0x0, 0x0, 0x0, 0x0)
        /home/travis/.gimme/versions/go1.5.linux.amd64/src/net/lookup.go:106 +0x
58
internal/singleflight.(*Group).doCall(0x8d9e00, 0x110d2cc0, 0x11150950, 0xc, 0x1
11509b0)
        /home/travis/.gimme/versions/go1.5.linux.amd64/src/internal/singleflight
/singleflight.go:93 +0x21
created by internal/singleflight.(*Group).DoChan
        /home/travis/.gimme/versions/go1.5.linux.amd64/src/internal/singleflight
/singleflight.go:86 +0x30d

goroutine 18 [runnable]:
github.com/go-fsnotify/fsnotify.(*Watcher).readEvents(0x110d2e10)
        /home/travis/gopath/src/github.com/go-fsnotify/fsnotify/windows.go:373
created by github.com/go-fsnotify/fsnotify.NewWatcher
        /home/travis/gopath/src/github.com/go-fsnotify/fsnotify/windows.go:46 +0
x2d5

goroutine 19 [runnable]:
github.com/gamexg/TcpRoute2/ufile.(*UFile).loop(0x110d5480)
        /home/travis/gopath/src/github.com/gamexg/TcpRoute2/ufile/ufile.go:261
created by github.com/gamexg/TcpRoute2/ufile.NewUFile
        /home/travis/gopath/src/github.com/gamexg/TcpRoute2/ufile/ufile.go:81 +0
x209

goroutine 20 [runnable]:
github.com/gamexg/TcpRoute2/ufile.(*UFile).down(0x110d5480, 0x110d56c0, 0x0, 0x1
)
        /home/travis/gopath/src/github.com/gamexg/TcpRoute2/ufile/ufile.go:116
created by github.com/gamexg/TcpRoute2/ufile.(*UFile).Add
        /home/travis/gopath/src/github.com/gamexg/TcpRoute2/ufile/ufile.go:211 +
0x57d

goroutine 21 [runnable]:
github.com/gamexg/TcpRoute2/ufile.(*UFile).down(0x110d5480, 0x110d5740, 0x0, 0x1
)
        /home/travis/gopath/src/github.com/gamexg/TcpRoute2/ufile/ufile.go:116
created by github.com/gamexg/TcpRoute2/ufile.(*UFile).Add
        /home/travis/gopath/src/github.com/gamexg/TcpRoute2/ufile/ufile.go:211 +
0x57d

goroutine 22 [runnable]:
main.(*DialClients).loop(0x110d2de0, 0x110d5480)
        /home/travis/gopath/src/github.com/GameXG/TcpRoute2/upstream_dialclients
.go:170
created by main.(*DialClients).Config
        /home/travis/gopath/src/github.com/GameXG/TcpRoute2/upstream_dialclients
.go:165 +0xaaf

goroutine 23 [runnable]:
net.(*ioSrv).ProcessRemoteIO(0x110eab48)
        /home/travis/.gimme/versions/go1.5.linux.amd64/src/net/fd_windows.go:135

created by net.startServer
        /home/travis/.gimme/versions/go1.5.linux.amd64/src/net/fd_windows.go:238
 +0xc9

goroutine 24 [chan receive, locked to thread]:
net.(*ioSrv).ProcessRemoteIO(0x110eab50)
        /home/travis/.gimme/versions/go1.5.linux.amd64/src/net/fd_windows.go:138
 +0xcc
created by net.startServer
        /home/travis/.gimme/versions/go1.5.linux.amd64/src/net/fd_windows.go:240
 +0x11e

goroutine 25 [runnable]:
github.com/gamexg/TcpRoute2/ufile.(*UFile).loop.func1(0x110d4600, 0x11150c20)
        /home/travis/gopath/src/github.com/gamexg/TcpRoute2/ufile/ufile.go:265
created by github.com/gamexg/TcpRoute2/ufile.(*UFile).loop
        /home/travis/gopath/src/github.com/gamexg/TcpRoute2/ufile/ufile.go:268 +
0x6b
```

**Comment by GameXG** [comment]
TcpRoute 的版本是？

>本地有简单的HTTP服务， http://127.0.0.1/file/hosts.txt 的内容为一行 127.0.0.1 localhost 。
>在配置中指定本地hosts报错，删除后错误消失。
>格式完全相同的 pgl.yoyo.org 的hosts不会引发问题。

测试了 127.0.0.1 http服务未开启，文件不存在及 127.0.0.1 localhost  内容，v0.5.1 没有复现成功。
最近对 hosts 进行过重写，可能已经修正了这个问题。不过发现了另一个问题，404的页面也会被当作 hosts 文件解析处理...

**Comment by GameXG** [comment]
>新加的几个功能的配置建议做一下判断，当缺少子项或者某选项不存在时，使用默认值启动，或者输出特>定的错误信息后退出。比如[[Hosts]]不存在时启动过程中会直接崩溃掉，必需在同目录新建一个hosts指定才可以顺利运行，但实际上hosts应该不属于必选配置。

[[hosts]] 不是必须存在的条目，允许不存在 hosts 配置。不过需要将 [[Hosts]] 和它下面的Path、UpdateInterval、Credit、Type行全部删掉才可以，否则会报错退出。
目前配置示例文件内容太多，比较乱，需要整理下了。

**Comment by puteulanus** [comment]
0.5.0
我去试试 0.5.1 。

**Comment by GameXG** [comment]
>顺便，指定与配置文件同目录的 whitelist.txt （Path="whitelist.txt"）之后似乎并没有加载白名单，在加入 google.com 之后依然可以正常访问。尝试过重启软件，依旧如此。

这个可能和白名单的 Type="suffix" 有关，suffix 时才会执行泛解析匹配， google.com 匹配 www.google.com ，否则可能 google.com 只匹配 www.google.com 。

另一个可能是 https://raw.githubusercontent.com/racaljk/hosts/master/hosts 造成的，这个包含 google 等网站的ip，使用它可以直连 google。

晕，刚刚查看了一下代码，最近对 hosts 的重写还没发布，这就发布为 0.5.2 。

**Comment by GameXG** [comment]
核对了 0.5.0 的代码，“panic: runtime error: invalid memory address or nil pointer dereference ” 的错误在hosts功能重写时已经更正了。

**Comment by puteulanus** [comment]
测试 0.5.1 依旧如此。
这是我的配置文件
```
[[Hosts]]
Path="hosts.txt"
Type="base"

[[Hosts]]
Path="http://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&showintro=0&mimetype=plaintext"
Type="base"
UpdateInterval="24h"

[[UpStreams.Whitelist]]
Path="whitelist.txt"
UpdateInterval="24h"
Type="suffix"

[[UpStreams.Blacklist]]
Path="blacklist.txt"
UpdateInterval="24h"
Type="suffix"
```
whitelist.txt 位于主程序同目录下，内容为 www.google.com 与 google.com 两行。
两个hosts一个为空，另一个所有项全为 127.0.0.1 ，是阻拦广告用的。
但谷歌首页依旧访问正常。

**Comment by GameXG** [comment]
是报错退出还是白名单无效？
如果是报错，错误信息是？

[[UpStreams.Whitelist]] 需要紧挨着 直连 的 UpStreams ，如果放到了 代理的 UpStreams 下面会作为代理的白名单生效，也就是 Whitelist 内的域名必定走代理。

对于 TcpRoute 而言，直连和代理都是一样的，质量和代理都允许指定自己的黑白名单。

**Comment by puteulanus** [comment]
看来是我对黑白名单的理解有误，我重新修改一下配置试试。

**Comment by GameXG** [comment]
配置文件示例也需要重新整理了，我自己看着都头疼。

 #48
